# Generated by Django 3.0.4 on 2020-04-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('user_fName', models.CharField(max_length=50)),
                ('user_sName', models.CharField(max_length=50)),
                ('user_other_Name', models.CharField(max_length=50, null=True)),
                ('user_pWord', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_name', models.CharField(max_length=30, unique=True)),
                ('user_image', models.ImageField(upload_to='static/profpics')),
            ],
        ),
    ]
