# Generated by Django 3.0.6 on 2020-06-13 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldsOfSpecialisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Field_Name', models.CharField(max_length=50, verbose_name='Field')),
                ('Field_Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Specialisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area_Of_Specialisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DevsPlatform.FieldsOfSpecialisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
