# Generated by Django 3.0.6 on 2020-06-13 12:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DevsPlatform', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Specialisation',
            new_name='UserSpecialisation',
        ),
    ]
