# Generated by Django 3.0.6 on 2020-06-13 13:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DevsPlatform', '0002_auto_20200613_1216'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userspecialisation',
            unique_together={('user', 'Area_Of_Specialisation')},
        ),
    ]
