# Generated by Django 3.0.6 on 2020-06-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevsPlatform', '0003_auto_20200613_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50, verbose_name='Event Name')),
                ('sheduled_date', models.DateField(verbose_name='Sheduled Date')),
                ('sheduled_venue', models.CharField(max_length=50, verbose_name='Venue')),
                ('sheduled_time', models.TimeField(verbose_name='Sheduled Time')),
                ('event_topic', models.CharField(max_length=50, verbose_name='Topic')),
            ],
        ),
    ]
