# Generated by Django 3.0.6 on 2020-06-13 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DevsPlatform', '0004_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
