# Generated by Django 3.0.6 on 2020-06-15 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DevsPlatform', '0005_auto_20200613_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentApproach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aproach_name', models.CharField(max_length=50)),
                ('aproach_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('project_start', models.DateField(verbose_name='Start time')),
                ('project_end', models.DateField(verbose_name='Completion Time')),
                ('project_aproach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DevsPlatform.DevelopmentApproach', verbose_name='Development Approach')),
                ('project_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DevsPlatform.FieldsOfSpecialisation')),
                ('project_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('date_of_creation', models.DateField(auto_now=True)),
                ('goal', models.CharField(blank=True, max_length=50, null=True)),
                ('team_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DevsPlatform.FieldsOfSpecialisation')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_role', models.CharField(choices=[(1, 'Chair'), (2, 'Vice-Chair'), (3, 'Secretary'), (4, 'Vice-Secretary'), (4, 'Treasurer'), (5, 'Other')], max_length=50)),
                ('member_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DevsPlatform.Team')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DevsPlatform.Project')),
            ],
        ),
    ]
