# Generated by Django 3.0.6 on 2020-06-15 11:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DevsPlatform', '0006_developmentapproach_project_projectparticipant_team_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='projectparticipant',
            unique_together={('participant_name', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('member_name', 'team')},
        ),
    ]
