# Generated by Django 3.0.6 on 2020-06-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevsPlatform', '0008_auto_20200615_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='member_role',
            field=models.IntegerField(choices=[(1, 'Chair'), (2, 'Vice-Chair'), (3, 'Secretary'), (4, 'Vice-Secretary'), (4, 'Treasurer'), (5, 'Other')]),
        ),
    ]
