# Generated by Django 3.0.6 on 2020-06-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevsPlatform', '0011_auto_20200620_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='member_role',
            field=models.CharField(choices=[('Chair', 'Chair'), ('Vice-Chair', 'Vice-Chair'), ('Secretary', 'Secretary'), ('Vice-Secretary', 'Vice-Secretary'), ('Vice-Secretary', 'Treasurer')], default=None, max_length=20),
        ),
    ]
