# Generated by Django 3.0.6 on 2020-06-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevsPlatform', '0014_auto_20200620_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='member_role',
            field=models.CharField(blank=True, choices=[('Chair', 'Chair'), ('Vice-Chair', 'Vice-Chair'), ('Secretary', 'Secretary'), ('Vice-Secretary', 'Vice-Secretary'), ('Vice-Secretary', 'Treasurer'), (None, 'None')], default=None, max_length=20, null=True),
        ),
    ]
