# Generated by Django 3.0.6 on 2020-06-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevsPlatform', '0015_auto_20200627_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='add_priviledge',
            field=models.IntegerField(choices=[(1, 'Only Head can add participants'), (2, 'Request first b4 joining'), (2, 'Free join')], default=2, verbose_name='Joining priviledge'),
        ),
        migrations.AddField(
            model_name='project',
            name='maximum_members',
            field=models.IntegerField(default=20),
        ),
    ]
