# Generated by Django 3.0.6 on 2020-07-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevsPlatform', '0016_auto_20200627_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='add_priviledge',
            field=models.IntegerField(choices=[(1, 'Only Head can add participants'), (2, 'Request first b4 joining'), (3, 'Free join')], default=3, verbose_name='Joining priviledge'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_end',
            field=models.DateField(verbose_name='Completion Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_start',
            field=models.DateField(verbose_name='Start Date'),
        ),
    ]
